USE papyrus;
LOAD DATA LOCAL INFILE 'C:\\Users\\80010-11-02\\Downloads\\vente.csv'
INTO TABLE vente
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(CODART,LIBART,UNIMES,STKALE,STKPHY,QTEANN);